# Generated by Django 5.2 on 2025-04-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Flex')], verbose_name='Combustível')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Audi'), (2, 'BMW'), (3, 'Chevrolet'), (4, 'Fiat'), (5, 'Ford'), (6, 'Honda'), (7, 'Hyundai'), (8, 'Jeep'), (9, 'Kia')], verbose_name='Marca')),
                ('cor', models.SmallIntegerField(choices=[(1, 'Preto'), (2, 'Branco'), (3, 'Prata'), (4, 'Vermelho'), (5, 'Azul'), (6, 'Verde')], verbose_name='Cor')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
        ),
    ]
