# Generated by Django 5.2 on 2025-04-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculos',
        ),
    ]
