# Generated by Django 5.2 on 2025-04-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_alter_veiculo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default=None, max_length=100, verbose_name='Modelo'),
        ),
    ]
